version: '3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:dev-alpine
    ports:
      - 8001:80
    restart: always
    logging:
      options:
        max-size: "10m"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
